import os

remote_urls = {
    'john_hopkins_repo': 'https://github.com/CSSEGISandData/COVID-19/archive/master.zip',
    'daily_reports_relative_path': 'COVID-19-master' + os.sep + 'csse_covid_19_data' + os.sep + 'csse_covid_19_daily_reports',
    'confirmed_time_series': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data'
                             '/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv',
    'recovered_time_series': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data'
                             '/csse_covid_19_time_series/time_series_covid19_recovered_global.csv',
    'deaths_time_series': 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data'
                          '/csse_covid_19_time_series/time_series_covid19_deaths_global.csv '

}

dataset_directory_path = os.getcwd() + os.sep + "data" + os.sep

country_code_dict = {'Afghanistan': 'AF',
                     'Angola': 'AO',
                     'Albania': 'AL',
                     'United Arab Emirates': 'AE',
                     'Argentina': 'AR',
                     'Armenia': 'AM',
                     'Australia': 'AU',
                     'Austria': 'AT',
                     'Azerbaijan': 'AZ',
                     'Burundi': 'BI',
                     'Bahrain': 'BH',
                     'Brunei': 'BN',  'Belgium': 'BE',
                     'Benin': 'BJ',
                     'Burkina Faso': 'BF',
                     'Bangladesh': 'BD',
                     'Bulgaria': 'BG',
                     'Bosnia and Herzegovina': 'BA',
                     'Belarus': 'BY',
                     'Belize': 'BZ',
                     'Bolivia': 'BO',
                     'Brazil': 'BR',
                     'Brunei Darussalam': 'BN',
                     'Bhutan': 'BT',
                     'Botswana': 'BW',
                     'Central African Republic': 'CF',
                     'Canada': 'CA',
                     'Switzerland': 'CH',
                     'Chile': 'CL',
                     'China': 'CN', "Cote d'Ivoire": 'CI',
                     'Cameroon': 'CM',
                     'Democratic Republic of the Congo': 'CD',
                     'Republic of Congo': 'CG',
                     'Colombia': 'CO',
                     'Costa Rica': 'CR',
                     'Cuba': 'CU',
                     'Cabo Verde': 'CV',
                     'Czech Republic': 'CZ',
                     'Germany': 'DE',
                     'Djibouti': 'DJ',
                     'Denmark': 'DK',
                     'Dominican Republic': 'DO',
                     'Algeria': 'DZ',
                     'Ecuador': 'EC',
                     'Egypt': 'EG',
                     'Eritrea': 'ER',
                     'Estonia': 'EE',
                     'Ethiopia': 'ET',
                     'Finland': 'FI',
                     'Fiji': 'FJ',
                     'Gabon': 'GA',
                     'United Kingdom': 'GB',
                     'Georgia': 'GE',
                     'Ghana': 'GH',
                     'Guinea': 'GN',
                     'Gambia': 'GM',
                     'Guinea-Bissau': 'GW',
                     'Equatorial Guinea': 'GQ',
                     'Greece': 'GR',
                     'Greenland': 'GL',
                     'Guatemala': 'GT',
                     'Guyana': 'GY',
                     'Honduras': 'HN',
                     'Croatia': 'HR',
                     'Haiti': 'HT',
                     'Hungary': 'HU',
                     'Indonesia': 'ID',
                     'India': 'IN',
                     'Ireland': 'IE',
                     'Iran': 'IR',
                     'Iraq': 'IQ',
                     'Iceland': 'IS',
                     'Israel': 'IL',
                     'Italy': 'IT',
                     'Jamaica': 'JM',
                     'Jordan': 'JO',
                     'Japan': 'JP',
                     'Kazakhstan': 'KZ',
                     'Kenya': 'KE',
                     'Kyrgyzstan': 'KG',
                     'Cambodia': 'KH',
                     'Korea, South': 'KR',
                     'Kosovo': 'XK',
                     'Kuwait': 'KW',
                     'Lao PDR': 'LA',
                     'Lebanon': 'LB',
                     'Liberia': 'LR',
                     'Libya': 'LY',
                     'Sri Lanka': 'LK',
                     'Lesotho': 'LS',
                     'Lithuania': 'LT',
                     'Luxembourg': 'LU',
                     'Latvia': 'LV',
                     'Morocco': 'MA',
                     'Moldova': 'MD',
                     'Madagascar': 'MG',
                     'Mexico': 'MX',
                     'Macedonia': 'MK',
                     'Mali': 'ML',
                     'Myanmar': 'MM',
                     'Montenegro': 'ME',
                     'Mongolia': 'MN',
                     'Mozambique': 'MZ',
                     'Mauritania': 'MR',
                     'Malawi': 'MW',
                     'Malaysia': 'MY',
                     'Namibia': 'NA',
                     'Niger': 'NE',
                     'Nigeria': 'NG',
                     'Nicaragua': 'NI',
                     'Netherlands': 'NL',
                     'Norway': 'NO',
                     'Nepal': 'NP',
                     'New Zealand': 'NZ',
                     'Oman': 'OM',
                     'Pakistan': 'PK',
                     'Panama': 'PA',
                     'Peru': 'PE',
                     'Philippines': 'PH',
                     'Papua New Guinea': 'PG',
                     'Poland': 'PL',
                     'Dem. Rep. Korea': 'KP',
                     'Portugal': 'PT',
                     'Paraguay': 'PY',
                     'Palestine': 'PS',
                     'Qatar': 'QA',
                     'Romania': 'RO',
                     'Russia': 'RU',
                     'Rwanda': 'RW',
                     'Western Sahara': 'EH',
                     'Saudi Arabia': 'SA',
                     'Sudan': 'SD',
                     'South Sudan': 'SS',
                     'Senegal': 'SN',
                     'Sierra Leone': 'SL',
                     'El Salvador': 'SV',
                     'Serbia': 'RS',
                     'Suriname': 'SR',
                     'Slovakia': 'SK',
                     'Slovenia': 'SI',
                     'Sweden': 'SE',
                     'Swaziland': 'SZ',
                     'Syria': 'SY',
                     'Chad': 'TD',
                     'Togo': 'TG',
                     'Thailand': 'TH',
                     'Tajikistan': 'TJ',
                     'Turkmenistan': 'TM',
                     'Timor-Leste': 'TL',
                     'Tunisia': 'TN',
                     'Turkey': 'TR',
                     'Taiwan': 'TW',
                     'Tanzania': 'TZ',
                     'Uganda': 'UG',
                     'Ukraine': 'UA',
                     'Uruguay': 'UY',
                     'United States': 'US',
                     'Uzbekistan': 'UZ',
                     'Venezuela': 'VE',
                     'Vietnam': 'VN',
                     'Vanuatu': 'VU',
                     'Yemen': 'YE',
                     'South Africa': 'ZA',
                     'Zambia': 'ZM',
                     'Zimbabwe': 'ZW',
                     'Somalia': 'SO',
                     'France': 'FR',
                     'Spain': 'ES',
                     'Aruba': 'AW',
                     'Anguilla': 'AI',
                     'Andorra': 'AD',
                     'Antigua and Barbuda': 'AG',
                     'Bahamas': 'BS',
                     'Bermuda': 'BM',
                     'Barbados': 'BB',
                     'Comoros': 'KM',
                     'Cape Verde': 'CV',
                     'Cayman Islands': 'KY',
                     'Dominica': 'DM',
                     'Falkland Islands': 'FK',
                     'Faeroe Islands': 'FO',
                     'Grenada': 'GD',
                     'Hong Kong': 'HK',
                     'Saint Kitts and Nevis': 'KN',
                     'Saint Lucia': 'LC',
                     'Liechtenstein': 'LI',
                     'Saint Martin (French)': 'MF',
                     'Maldives': 'MV',
                     'Malta': 'MT',
                     'Montserrat': 'MS',
                     'Mauritius': 'MU',
                     'New Caledonia': 'NC',
                     'Nauru': 'NR',
                     'Pitcairn Islands': 'PN',
                     'Puerto Rico': 'PR',
                     'French Polynesia': 'PF',
                     'Singapore': 'SG',
                     'Solomon Islands': 'SB',
                     'São Tomé and Principe': 'ST',
                     'Saint Martin (Dutch)': 'SX',
                     'Seychelles': 'SC',
                     'Turks and Caicos Islands': 'TC',
                     'Tonga': 'TO',
                     'Trinidad and Tobago': 'TT',
                     'Saint Vincent and the Grenadines': 'VC',
                     'British Virgin Islands': 'VG',
                     'United States Virgin Islands': 'VI',
                     'Cyprus': 'CY',
                     'Reunion (France)': 'RE',
                     'Mayotte (France)': 'YT',
                     'Martinique (France)': 'MQ',
                     'Guadeloupe (France)': 'GP',
                     'Curaco (Netherlands)': 'CW',
                     'Canary Islands (Spain)': 'IC',
                     'Diamond Princess': 'DIA_P',
                     'MS Zaandam': 'MSZ',
                     'Holy See': 'VA',
                     'Laos': 'LAO',
                     'Monaco': 'MCO',
                     'North Macedonia': 'MKD',
                     'San Marino': 'SMR'
                    }
